# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='counters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(default=None, max_length=255)),
                ('service_id', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('msisdn', models.IntegerField(default=None, unique=True)),
                ('role', models.CharField(default=None, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_no', models.IntegerField(default=None)),
                ('teller_id', models.IntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='tellers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('counter_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('teller_id', models.IntegerField(default=0)),
                ('ticket', models.IntegerField(default=None)),
                ('status', models.IntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
